import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { client } from '../lib/client';
import Heroslider from '../Components/HeroSlider';
import HomeCategory from '../Components/HomeCategory';
import Newsletter from '../Components/Newsletter';

export default function Home({ products, bannerData, categoryData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Lumena</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heroslider bannerData={bannerData} />
      <HomeCategory categoryData={categoryData} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);
  const categoryQuery = '*[_type == "category"]';
  const categoryData = await client.fetch(categoryQuery);

  return {
    props: { products, bannerData, categoryData },
  };
};
