import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { client } from '../lib/client';
import Heroslider from '../Components/HeroSlider';

export default function Home({ products, bannerData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heroslider bannerData={bannerData} />
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
